[project]
name = "mcp-terminal-server"
version = "0.1.0"
description = "MCP server for terminal and file operations"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp>=1.0.0",
    "httpx>=0.27.0"
]

[tool.uv]
dev-dependencies = []